# Assignment-2

In [3]:
import numpy as np

# Q.1. Array Creation

### a. Create a 1-dimensional array of integers from 1 to 10.

In [4]:
a = np.array(range(1, 11))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### b. Create a 2-dimensional array with random float values of shape(3, 4)

In [5]:
b = np.random.rand(3, 4)
b

array([[0.93505512, 0.08430474, 0.21042985, 0.27867565],
       [0.63788816, 0.66435338, 0.83763198, 0.31237785],
       [0.74455922, 0.27750845, 0.16765813, 0.79253817]])

### c. Create a 3-dimensional array of zeros with shape(2, 3, 4)

In [6]:
c = np.zeros((2, 3, 4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Q.2. Array Operations

#### a. Given two 1-dimensional arrays, perform element-wise addition, subtraction, multiplication and division

In [8]:
d = np.array([1, 2, 3])
e = np.array([4, 5, 6])

f = d + e
f

array([5, 7, 9])

In [9]:
g = d - e
g

array([-3, -3, -3])

In [10]:
h = d * e
h

array([ 4, 10, 18])

In [11]:
i = d / e
i

array([0.25, 0.4 , 0.5 ])

### b. Calculate the mean, median and standard deviation of a given 1-dimensional array

In [12]:
j = np.array([11, 12, 13, 14, 15])

mean_value = np.mean(j)
mean_value

13.0

In [13]:
median_value = np.median(j)
median_value

13.0

In [14]:
std_dev = np.std(j)
std_dev

1.4142135623730951

### c. Reshape a 1-dimensional array into a 2-dimensional array of shape (3, 4)

In [19]:
k = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
l = k.reshape(3, 4)
l

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Q.3. Array Indexing and Slicing

### a. Extract the first row and last column of a 2-dimensional array

In [23]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

first_row = m[0]
last_column = m[:, -1]

print (first_row)
print (last_column)

[1 2 3]
[3 6 9]


### b. Reverse the order of elements in a 1-dimensional array

In [25]:
n = np.array([1, 2, 3])

reverse_array = n[::-1]
reverse_array

array([3, 2, 1])

### c. Select elements from a 2-dimensional array that satisfy a specific 
condition (e.g., values greater than a certain threshold.

In [26]:
o = np.array([[1,7,9],[6,8,4]])
threshold= 4
greater = o > 4
greater

array([[False,  True,  True],
       [ True,  True, False]])

# Q.4. Array Broadcasting

### a. Add a scalar value to each element of a 2-dimensional array

In [27]:
p = np.array([[1,7,9],[6,8,4]])
scalar_value = 6

result = p + scalar_value
result

array([[ 7, 13, 15],
       [12, 14, 10]])

### b. Multiply a 1-dimensional array with a 2-dimensional array, leveraging Numpy's broadcasting rules

In [28]:
q = np.array([1, 2, 3])
r = np.array([[4, 5, 6], [7, 8, 9]])

mul = q * r
mul

array([[ 4, 10, 18],
       [ 7, 16, 27]])

# Q.5. Linear Algebra

### a. Calculate the dot product of two 1-dimensional arrays

In [29]:
s = np.array([1,2,3])
t = np.array([4,3,6])

result = np.dot(s, t)
result

28

### b. Compute the matrix multiplication of two 2-dimensional arrays

In [30]:
u = np.array([[1,2,3],[6,3,2]])
v = np.array([[1,3,2],[2,1,3]])
multi = u* v
multi

array([[ 1,  6,  6],
       [12,  3,  6]])

### c. Find the inverse and determinant of a square matrix

In [31]:
w = np.array([[1,2],[3,34]])
inv = np.linalg.inv(w)
inv

array([[ 1.21428571, -0.07142857],
       [-0.10714286,  0.03571429]])

In [32]:
det = np.linalg.det(w)
det

28.00000000000001